using System.Collections.Generic;

namespace ChurchServer.Web.ApiModels
{
    // ApiModel DTOs are used by ApiController classes and are typically kept in a side-by-side folder
    public class MemberDTO : CreateMemberDTO
    {
        public int Id { get; set; }
        //public List<ToDoItemDTO> Items = new();
    }

    // Creation DTOs should not include an ID if the ID will be generated by the back end
    public class CreateMemberDTO
    {
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string SurName { get; set; }
        public string LastName { get; set; }
    }
}
